name: Deploy to Azure

on:
  push:
    branches: [ "main" ] # Спрацьовує при пуші в main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Копіюємо код із репозиторію на ранер
      # https://docs.github.com/en/actions
      - name: Checkout code
        uses: actions/checkout@v4

      # Логінимося в Azure (використовуючи секрети)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Логінимося в ACR, щоб мати змогу пушити образи
      - name: ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # Azure Container Registry не дав зібрати образи через студентську підписку, 
      # тому спробуємо збирати образи в Github і пушити їх в ACR
      - name: Build on Github and Push to ACR
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/cms-service:${{ github.sha }} -f src/CMS.Service/Dockerfile .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/cms-service:${{ github.sha }}
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/gateway:${{ github.sha }} -f src/Gateway.Yarp/Dockerfile .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/gateway:${{ github.sha }}

      # Оновлюємо Container Apps новими образами
      - name: Update Container Apps
        run: |
          az containerapp update --name cms-app --resource-group DistributedSystem-RG --image ${{ secrets.ACR_NAME }}.azurecr.io/cms-service:${{ github.sha }}
          az containerapp update --name gateway-app --resource-group DistributedSystem-RG --image ${{ secrets.ACR_NAME }}.azurecr.io/gateway:${{ github.sha }}